### PR TITLE
Add sharedHardware

### PR DESCRIPTION
**Pull request by Fl0x23**
I have expanded the request to include shared hardware.
image

### CODE REVIEW

**Comment by vciancio** [comment]
Could you put the _sharedHardware_ object underneath _hardware_ instead of info? Might make more sense. As well, maybe can just name it _shared_ instead of _sharedHardware_, what do you think?

**Comment by Fl0x23** [comment]
I thought _hardware_ and _info_ are splitted into yagna requests and others. The files _golem.py_ and _hardware.py_ are also prepared in this way. But the user will read the title _hardware_ and _info_ rather than the code, so it certainly makes sense to locate it under _hardware_. If it is under the subtitle _hardware_, _shared_ should be understandable. I will write a new commit.

**Comment by vciancio** [comment]
The issue here though now is that for a single request, we're instantiating _GolemStatus_ twice, therefore running all of the yanga commands twice. So we'd want to pass  _GolemStatus_  as an argument to the methods and construct it at the entrypoint.

**Comment by Fl0x23** [comment]
Of course I don't want that. Thanks for the hint. :+1: 
At first i had in the _golem_, _hardware_stats_ and _stats_all_  methods the same variable name. It would work, but I think the confusion risk is better if it is different.

**Pull request merged**
